language: swift
matrix:
    include:
        - osx_image: xcode10.1
script:
    - xcodebuild test -scheme CalendarKit-Package | xcpretty -c
    - bash <(curl -s https://codecov.io/bash)
notifications:
    email: false